---
- name: Install nginx
  apt: name=nginx state=present

- name: Delete default confs
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Delete default confs
  file: path=/etc/nginx/sites-available/default state=absent

- name: Default default confs
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/sites-available/magento

- name: Make symlink
  file: src=/etc/nginx/sites-available/magento dest=/etc/nginx/sites-enabled/magento state=link
  notify: restart nginx
