---
- name: Provision server
  rax:
    credentials: "{{ pyrax_creds_file }}"
    region: "{{ rs_region }}"
    name: admin
    auto_increment: no
    count: 1
    exact_count: yes
    flavor: performance1-2
    image: "{{ server_image }}"
    key_name: "{{ server_keypair }}"
    networks:
      - public
      - private
      - "{{ network.networks[0].id }}"
    wait: yes
    state: present
    group: admin
  register: rax_admin

- name: Add server to host
  add_host:
    hostname: "{{ item.name }}"
    ansible_ssh_host: "{{ item.rax_accessipv4 }}"
    groupname: admin
  with_items: rax_admin.success
  when: rax_admin.action == 'create'
