---
- name: Debian | Supported OS
  set_fact:
    base_supported_os: True

- name: Debian | setup monitoring agent apt key
  apt_key: id=D05AB914 url='https://monitoring.api.rackspacecloud.com/pki/agent/linux.asc' state=present

- name: Ubuntu | setup monitoring agent apt repository
  apt_repository: repo='deb http://stable.packages.cloudmonitoring.rackspace.com/{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}-x86_64 cloudmonitoring main' state=present
  when: ansible_distribution == "Ubuntu"

- name: Debian | setup monitoring agent apt repository
  apt_repository: repo='deb http://stable.packages.cloudmonitoring.rackspace.com/{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}-x86_64 cloudmonitoring main' state=present
  when: ansible_distribution == "Debian"

- name: Debian | install monitoring agent
  apt: name=rackspace-monitoring-agent state=present update_cache=yes cache_valid_time=86400
