---
- name: RedHat | Supported OS
  set_fact:
    base_supported_os: True

- name: RedHat | add rpm key
  rpm_key: state=present key=https://monitoring.api.rackspacecloud.com/pki/agent/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.asc

- name: RedHat | setup repo file
  template: src=RedHat.repo.j2 dest=/etc/yum.repos.d/rackspace-cloud-monitoring.repo owner=root group=root mode=0644

- name: RedHat | install the agent
  yum: name=rackspace-monitoring-agent state=present
